name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
      # The following variable indicates the size of the subset array in the matrix below.
      SUBSET_SIZE: 12
    strategy:
      fail-fast: false
      matrix:
        # The size of this array should match SUBSET_SIZE above.
        subset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: asset_tracker_v2

      - name: Initialize
        working-directory: asset_tracker_v2
        run: |
          west init -l .
          west update --narrow -o=--depth=1

      - name: Install deps
        run: |
            apt-get update
            apt-get install -y ruby-full
            pip3 install -r nrf/scripts/requirements.txt

      - name: Twister build
        working-directory: asset_tracker_v2
        run: |
          ../zephyr/scripts/twister -i -v --subset ${{ matrix.subset }}/${{ env.SUBSET_SIZE }} --build-only -G --board-root ../nrf/boards/ --testsuite-root ./app/asset_tracker_v2/

      - name: Twister Tests
        working-directory: asset_tracker_v2
        run: |
          ../zephyr/scripts/twister -i -v -G --subset ${{ matrix.subset }}/${{ env.SUBSET_SIZE }} --board-root ../nrf/boards/ --testsuite-root ./app/asset_tracker_v2/tests/
