name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: asset_tracker_v2

      - name: Initialize
        working-directory: asset_tracker_v2
        run: |
          west init -l .
          west update --narrow -o=--depth=1

      - name: Install deps
        run: |
            apt-get update
            apt-get install -y ruby-full
            pip3 install -r nrf/scripts/requirements.txt

      - name: Twister Tests
        working-directory: asset_tracker_v2
        run: |
          ../zephyr/scripts/twister -i -v -G --board-root ../nrf/boards/ --testsuite-root ./app/asset_tracker_v2/tests/
